name: Deploy Backend Infrastructure

on:
  push:
    branches: [main]
    paths:
      - "infra/**"
      - "lambda_function.py"
      - ".github/workflows/deploy-backend.yml"

jobs:
  terraform_backend:
    name: Apply Terraform Infra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Check Terraform Version
        run: terraform -version
        
      - name: Debug token presence
        run: echo "TF_API_TOKEN is set"  # DO NOT echo the value
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      
      - name: Terraform Init
        working-directory: infra
        run: terraform init
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}


      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve

      - name: Output API Gateway URL
        working-directory: infra
        run: terraform output -raw api_gateway_url > ../api_url.txt

      - name: Output CloudFront ID
        working-directory: infra
        run: terraform output -raw cloudfront_distribution_id > ../cloudfront_id.txt

      - name: Upload API URL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-url
          path: api_url.txt

      - name: Upload CloudFront ID Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cloudfront-id
          path: cloudfront_id.txt
