name: Terraform Import

on:
  workflow_dispatch:

env:
  TF_VAR_alert_email:   ${{ secrets.ALERT_EMAIL_ADDRESS }}
  TF_VAR_project_name:  ${{ secrets.PROJECT_NAME }}
  TF_VAR_aws_region:    ${{ secrets.AWS_REGION }}

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure Terraform Cloud credentials
        run: |
          mkdir -p ~/.terraform.d
          cat > ~/.terraform.d/credentials.tfrc.json <<EOF
          {
            "credentials": {
              "app.terraform.io": {
                "token": "${{ secrets.TF_API_TOKEN }}"
              }
            }
          }
          EOF

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.7"

      - name: Terraform Init
        working-directory: monitoring
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: monitoring
        run: terraform validate

      - name: Import IAM Role
        working-directory: monitoring
        run: terraform import aws_iam_role.canary_role resume-monitoring-canary-role

      - name: Import S3 Bucket
        working-directory: monitoring
        run: terraform import aws_s3_bucket.artifacts canary-artifacts-b143dc4d

      - name: Import S3 SSE Configuration
        working-directory: monitoring
        run: terraform import aws_s3_bucket_server_side_encryption_configuration.artifacts_sse canary-artifacts-b143dc4d

      - name: Import S3 Versioning
        working-directory: monitoring
        run: terraform import aws_s3_bucket_versioning.canary_artifacts_versioning canary-artifacts-b143dc4d

      # — Add any other imports here — 
      # - name: Import IAM Policy Attachment
      #   working-directory: monitoring
      #   run: terraform import aws_iam_role_policy_attachment.canary_attach <attachment-id>

      - name: Terraform Plan (post-import)
        working-directory: monitoring
        run: terraform plan -input=false
