name: Terraform Monitoring

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_VAR_alert_email: ${{ secrets.ALERT_EMAIL_ADDRESS }}
  TF_VAR_project_name: ${{ secrets.PROJECT_NAME }}
  TF_VAR_aws_region:   ${{ secrets.AWS_REGION }}

jobs:
  monitoring:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.7"

      - name: Terraform Init
        working-directory: monitoring
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: monitoring
        run: terraform validate

      - name: Terraform Plan
        working-directory: monitoring
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        working-directory: monitoring
        run: terraform apply -input=false -auto-approve tfplan
