name: One-Time Import Canary Role

on:
  workflow_dispatch:

jobs:
  import_canary_role:
    name: Import existing IAM Role
    runs-on: ubuntu-latest

    # All "run" steps below will execute in the ./monitoring folder
    defaults:
      run:
        working-directory: ./monitoring

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            eu-west-2

      - name: Terraform Init
        run: terraform init -input=false

      - name: Import Canary Role
        run: terraform import aws_iam_role.canary_role resume-monitoring-canary-role
